# Generated by Django 5.0 on 2023-12-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("intensity", models.FloatField(blank=True, null=True)),
                ("sector", models.TextField(blank=True, null=True)),
                ("topic", models.TextField(blank=True, null=True)),
                ("insight", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("region", models.TextField(blank=True, null=True)),
                ("start_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("impact", models.IntegerField(blank=True, null=True)),
                ("added", models.DateTimeField(blank=True, null=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("relevance", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pestle", models.TextField(blank=True, null=True)),
                ("source", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("likelihood", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
