# Generated by Django 5.0 on 2023-12-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articledata",
            name="url",
            field=models.URLField(blank=True, max_length=20000, null=True),
        ),
    ]
